<?php
/**
 * Eternizer.
 *
 * @copyright Michael Ueberschaer
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package Eternizer
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://www.webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.4 (http://modulestudio.de) at Sat Dec 31 13:59:03 CET 2011.
 */

/**
 * This is the User api helper class.
 */
class Eternizer_Api_User extends Eternizer_Api_Base_User
{
    /**
     * get available User panel links
     *
     * @return array Array of admin links
     */
    public function getlinks()
    {
        $links = array();

        if (SecurityUtil::checkPermission($this->name . '::', '::', ACCESS_ADMIN)) {
            $links[] = array('url' => ModUtil::url($this->name, 'admin', 'main'),
                'text' => $this->__('Backend'),
                'title' => $this->__('Switch to administration area.'),
                'class' => 'z-icon-es-options');
        }
        if (SecurityUtil::checkPermission($this->name . '::', '::', ACCESS_READ)) {
            $links[] = array('url' => ModUtil::url($this->name, 'user', 'view', array('ot' => 'entry')),
                'text' => $this->__('Entries'),
                'title' => $this->__('Entry list'));
        }
        if (UserUtil::isLoggedIn() == true) {
            if (SecurityUtil::checkPermission($this->name . '::', '::', ACCESS_READ)) {
                $links[] = array('url' => ModUtil::url($this->name, 'user', 'view', array('ot' => 'entry',
                    'select' => 'mine')),
                    'text' => $this->__('My Entries'),
                    'title' => $this->__('View of my entries'));
            }
        }
        $formposition = ModUtil::getVar($this->name, 'formposition');
        if ($formposition == 'menue') {
            if (SecurityUtil::checkPermission($this->name . '::', '::', ACCESS_COMMENT)) {
                $links[] = array('url' => ModUtil::url($this->name, 'user', 'edit', array('ot' => 'entry')),
                    'text' => $this->__('New Entry'),
                    'title' => $this->__('Make a new entry'));
            }
        }


        return $links;
    }
}
