<?php
/**
 * Eternizer.
 *
 * @copyright Michael Ueberschaer
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package Eternizer
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://www.webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.4 (http://modulestudio.de) at Sat Dec 31 13:59:03 CET 2011.
 */

/**
 * This handler class handles the page events of the Form called by the Eternizer_user_edit() function.
 * It collects common functionality required by different object types.
 */
class Eternizer_Form_Handler_User_Edit extends Eternizer_Form_Handler_User_Base_Edit
{
    // feel free to extend the base handler class here
}
