services:
    # Entity factory classes
    mu_eternizer_module.entry_factory:
        class: MU\EternizerModule\Entity\Factory\EntryFactory
        arguments: ["@doctrine.orm.entity_manager", MU\EternizerModule\Entity\EntryEntity]
    
