services:
    # Event subscriber and listener classes
    mu_eternizer_module.core_listener:
        class: "MU\\EternizerModule\\Listener\\CoreListener"
        tags:
            - { name: kernel.event_subscriber }
    
    mu_eternizer_module.kernel_listener:
        class: "MU\\EternizerModule\\Listener\\KernelListener"
        tags:
            - { name: kernel.event_subscriber }
    
    mu_eternizer_module.installer_listener:
        class: "MU\\EternizerModule\\Listener\\InstallerListener"
        tags:
            - { name: kernel.event_subscriber }
    
    mu_eternizer_module.moduledispatch_listener:
        class: "MU\\EternizerModule\\Listener\\ModuleDispatchListener"
        tags:
            - { name: kernel.event_subscriber }
    
    mu_eternizer_module.mailer_listener:
        class: "MU\\EternizerModule\\Listener\\MailerListener"
        tags:
            - { name: kernel.event_subscriber }
    
    mu_eternizer_module.page_listener:
        class: "MU\\EternizerModule\\Listener\\PageListener"
        tags:
            - { name: kernel.event_subscriber }
    
    mu_eternizer_module.theme_listener:
        class: "MU\\EternizerModule\\Listener\\ThemeListener"
        tags:
            - { name: kernel.event_subscriber }
    
    mu_eternizer_module.view_listener:
        class: "MU\\EternizerModule\\Listener\\ViewListener"
        tags:
            - { name: kernel.event_subscriber }
    
    mu_eternizer_module.userlogin_listener:
        class: "MU\\EternizerModule\\Listener\\UserLoginListener"
        tags:
            - { name: kernel.event_subscriber }
    
    mu_eternizer_module.userlogout_listener:
        class: "MU\\EternizerModule\\Listener\\UserLogoutListener"
        tags:
            - { name: kernel.event_subscriber }
    
    mu_eternizer_module.user_listener:
        class: "MU\\EternizerModule\\Listener\\UserListener"
        tags:
            - { name: kernel.event_subscriber }
    
    mu_eternizer_module.userregistration_listener:
        class: "MU\\EternizerModule\\Listener\\UserRegistrationListener"
        tags:
            - { name: kernel.event_subscriber }
    
    mu_eternizer_module.users_listener:
        class: "MU\\EternizerModule\\Listener\\UsersListener"
        tags:
            - { name: kernel.event_subscriber }
    
    mu_eternizer_module.group_listener:
        class: "MU\\EternizerModule\\Listener\\GroupListener"
        tags:
            - { name: kernel.event_subscriber }
    
    mu_eternizer_module.thirdparty_listener:
        class: "MU\\EternizerModule\\Listener\\ThirdPartyListener"
        tags:
            - { name: kernel.event_subscriber }
    
