services:
    # Helper classes
    mu_eternizer_module.controller_helper:
        class: MU\EternizerModule\Helper\ControllerHelper
        arguments: ["@service_container", "@translator.default", "@session", "@logger"]
    
    mu_eternizer_module.hook_helper:
        class: MU\EternizerModule\Helper\HookHelper
        arguments: ["@hook_dispatcher"]
    
    mu_eternizer_module.listentries_helper:
        class: MU\EternizerModule\Helper\ListEntriesHelper
        arguments: ["@translator.default"]
    
    mu_eternizer_module.model_helper:
        class: MU\EternizerModule\Helper\ModelHelper
        arguments: ["@service_container"]
    
    mu_eternizer_module.notification_helper:
        class: MU\EternizerModule\Helper\NotificationHelper
        arguments: ["@translator.default", "@session", "@router", "@kernel", "@request_stack", "@zikula_extensions_module.api.variable", "@twig", "@zikula_mailer_module.api.mailer", "@mu_eternizer_module.workflow_helper"]
       
    mu_eternizer_module.selection_helper:
        class: MU\EternizerModule\Helper\SelectionHelper
        arguments: ["@service_container", "@doctrine.orm.entity_manager", "@translator.default", "@mu_eternizer_module.controller_helper"]
    
    mu_eternizer_module.view_helper:
        class: MU\EternizerModule\Helper\ViewHelper
        arguments: ["@service_container", "@translator.default"]
    
    mu_eternizer_module.workflow_helper:
        class: MU\EternizerModule\Helper\WorkflowHelper
        arguments: ["@service_container", "@translator.default"]
        
    mu_eternizer_module.captcha_helper:
        class: MU\EternizerModule\Helper\CaptchaHelper
        lazy: true
        arguments: ["@translator.default", "@zikula_extensions_module.api.variable", "@zikula_permissions_module.api.permission", "@mu_eternizer_module.environment_helper", "@jms_i18n_routing.router", "@session"]
        
    mu_eternizer_module.environment_helper:
        class: MU\EternizerModule\Helper\EnvironmentHelper
        lazy: true
        arguments: ["@kernel", "@translator.default", "@zikula_extensions_module.api.variable", "@session"]
