services:
    mu_eternizer_module.link_container:
        class: MU\EternizerModule\Container\LinkContainer
        arguments:
            - "@translator.default"
            - "@router"
            - "@zikula_permissions_module.api.permission"
            - "@mu_eternizer_module.controller_helper"
            - "@zikula_extensions_module.api.variable"
            - "@zikula_users_module.current_user"
        tags:
            - { name: zikula.link_container }
