<?php
/**
 * Eternizer.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\EternizerModule;

use MU\EternizerModule\Base\AbstractEternizerEvents;

/**
 * Events definition implementation class.
 */
class EternizerEvents extends AbstractEternizerEvents
{
    // feel free to extend the events definition here
}
