<?php
/**
 * Eternizer.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\EternizerModule\Form\Plugin;

use MU\EternizerModule\Form\Plugin\Base\AbstractItemSelector;

/**
 * Item selector plugin implementation class.
 */
class ItemSelector extends AbstractItemSelector
{
    // feel free to add your customisation here
}
