<?php
/**
 * Eternizer.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link http://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace MU\EternizerModule\Form\DataTransformer;

use MU\EternizerModule\Form\DataTransformer\Base\AbstractUserFieldTransformer;

/**
 * User field transformer implementation class.
 *
 * This data transformer treats user fields.
 */
class UserFieldTransformer extends AbstractUserFieldTransformer
{
    // feel free to add your customisation here
}
