<?php
/**
 * Eternizer.
 *
 * @copyright Michael Ueberschaer
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package Eternizer
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://www.webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.4 (http://modulestudio.de) at Tue Jan 03 13:01:47 CET 2012.
 */

/**
 * This is the Admin api helper class.
 */
class Eternizer_Api_Admin extends Eternizer_Api_Base_Admin
{
    // feel free to add own api methods here
}
