<?php
/**
 * Eternizer.
 *
 * @copyright Michael Ueberschaer
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package Eternizer
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://www.webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.4 (http://modulestudio.de) at Sat Dec 31 13:59:03 CET 2011.
 */


/**
 * Validator class for encapsulating entity validation methods.
 *
 * This is the concrete validation class for entry entities.
 */
class Eternizer_Entity_Validator_Entry extends Eternizer_Entity_Validator_Base_Entry
{
    // here you can add custom validation methods or override existing checks
}
