<?php
/**
 * Eternizer.
 *
 * @copyright Michael Ueberschaer
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package Eternizer
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://www.webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.3 (http://modulestudio.de) at Fri Dec 30 18:01:17 CET 2011.
 */

/**
 * This handler class handles the page events of the Form called by the Eternizer_admin_edit() function.
 * It aims on the entry object type.
 */
class Eternizer_Form_Handler_Admin_Entry_Edit extends Eternizer_Form_Handler_Base_Admin_Entry_Edit
{
    // feel free to extend the base handler class here
}
