<?php
/**
 * Eternizer.
 *
 * @copyright Michael Ueberschaer
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package Eternizer
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://www.webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.4 (http://modulestudio.de) at Wed Jan 04 16:43:44 CET 2012.
 */

/**
 * This handler class handles the page events of the Form called by the Eternizer_admin_edit() function.
 * It aims on the entry object type.
 */
class Eternizer_Form_Handler_Admin_Entry_Edit extends Eternizer_Form_Handler_Admin_Entry_Base_Edit
{
    /**
     * Method stub for own additions in subclasses.
     *
     * @depreciated to be removed in favour of postInitialize().
     */
    protected function initializeAdditions()
    {
        // We rule the position of the form
        $formposition = ModUtil::getVar($this->name, 'formposition');

        //We build the dropdownlist for moderation
        $moderation = Eternizer_Util_Controller::getKindOfStatus();

        $entry = $this->view->get_template_vars('entry');
        $entry['obj_statusItems'] = $moderation;
        $this->view->assign('entry', $entry);

        // We assign to the template
        $this->view->assign('formposition', $formposition);
    }
}
