<?php
/**
 * Eternizer.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://www.webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace MU\EternizerModule\Form\Base;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Zikula\Common\Translator\TranslatorInterface;
use Zikula\Common\Translator\TranslatorTrait;
use Zikula\ExtensionsModule\Api\VariableApi;
use Zikula\GroupsModule\Entity\RepositoryInterface\GroupRepositoryInterface;

/**
 * Configuration form type base class.
 */
abstract class AbstractAppSettingsType extends AbstractType
{
    use TranslatorTrait;

    /**
     * @var VariableApi
     */
    protected $variableApi;

    /**
     * @var array
     */
    protected $modVars;

    /**
     * AppSettingsType constructor.
     *
     * @param TranslatorInterface      $translator      Translator service instance
     * @param VariableApi              $variableApi     VariableApi service instance
     * @param GroupRepositoryInterface $groupRepository GroupRepository service instance
     */
    public function __construct(TranslatorInterface $translator, VariableApi $variableApi, GroupRepositoryInterface $groupRepository)
    {
        $this->setTranslator($translator);
        $this->variableApi = $variableApi;
        $this->modVars = $this->variableApi->getAll('MUEternizerModule');

        foreach (['moderationGroupForEntries'] as $groupFieldName) {
            $groupId = intval($this->modVars[$groupFieldName]);
            if ($groupId < 1) {
                $groupId = 2; // fallback to admin group
            }
            $this->modVars[$groupFieldName] = $groupRepository->find($groupId);
        }
    }

    /**
     * Sets the translator.
     *
     * @param TranslatorInterface $translator Translator service instance
     */
    public function setTranslator(/*TranslatorInterface */$translator)
    {
        $this->translator = $translator;
    }

    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $this->addVariablesFields($builder, $options);
        $this->addModerationFields($builder, $options);
        $this->addListviewsFields($builder, $options);

        $builder
            ->add('save', 'Symfony\Component\Form\Extension\Core\Type\SubmitType', [
                'label' => $this->__('Update configuration'),
                'icon' => 'fa-check',
                'attr' => [
                    'class' => 'btn btn-success'
                ]
            ])
            ->add('cancel', 'Symfony\Component\Form\Extension\Core\Type\SubmitType', [
                'label' => $this->__('Cancel'),
                'icon' => 'fa-times',
                'attr' => [
                    'class' => 'btn btn-default',
                    'formnovalidate' => 'formnovalidate'
                ]
            ])
        ;
    }

    /**
     * Adds fields for variables fields.
     *
     * @param FormBuilderInterface $builder The form builder
     * @param array                $options The options
     */
    public function addVariablesFields(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('mail', 'Symfony\Component\Form\Extension\Core\Type\TextType', [
                'label' => $this->__('Mail') . ':',
                'required' => false,
                'data' => $this->modVars['mail'],
                'empty_data' => '',
                'attr' => [
                    'title' => $this->__('Enter the mail.')
                ],'max_length' => 255
            ])
            ->add('order', 'Symfony\Component\Form\Extension\Core\Type\ChoiceType', [
                'label' => $this->__('Order') . ':',
                'required' => false,
                'data' => $this->modVars['order'],
                'empty_data' => '',
                'attr' => [
                    'title' => $this->__('Choose the order.')
                ],'choices' => [
                    $this->__('Descending') => 'descending'
                    ,$this->__('Ascending') => 'ascending'
                ],
                'choices_as_values' => true,
                'multiple' => false
            ])
            ->add('moderate', 'Symfony\Component\Form\Extension\Core\Type\ChoiceType', [
                'label' => $this->__('Moderate') . ':',
                'required' => false,
                'data' => $this->modVars['moderate'],
                'empty_data' => '',
                'attr' => [
                    'title' => $this->__('Choose the moderate.')
                ],'choices' => [
                    $this->__('Nothing') => 'nothing'
                    ,$this->__('Guests') => 'guests'
                    ,$this->__('All') => 'all'
                ],
                'choices_as_values' => true,
                'multiple' => false
            ])
            ->add('formposition', 'Symfony\Component\Form\Extension\Core\Type\ChoiceType', [
                'label' => $this->__('Formposition') . ':',
                'required' => false,
                'data' => $this->modVars['formposition'],
                'empty_data' => '',
                'attr' => [
                    'title' => $this->__('Choose the formposition.')
                ],'choices' => [
                    $this->__('Above') => 'above'
                    ,$this->__('Below') => 'below'
                    ,$this->__('Menue') => 'menue'
                ],
                'choices_as_values' => true,
                'multiple' => false
            ])
            ->add('ipsave', 'Symfony\Component\Form\Extension\Core\Type\CheckboxType', [
                'label' => $this->__('Ipsave') . ':',
                'required' => false,
                'data' => (bool)$this->modVars['ipsave'],
                'attr' => [
                    'title' => $this->__('The ipsave option.')
                ],
            ])
            ->add('editentries', 'Symfony\Component\Form\Extension\Core\Type\CheckboxType', [
                'label' => $this->__('Editentries') . ':',
                'required' => false,
                'data' => (bool)$this->modVars['editentries'],
                'attr' => [
                    'title' => $this->__('The editentries option.')
                ],
            ])
            ->add('period', 'Symfony\Component\Form\Extension\Core\Type\IntegerType', [
                'label' => $this->__('Period') . ':',
                'label_attr' => [
                    'class' => 'tooltips',
                    'title' => $this->__('Here we can decide how long a user may edit his entry; input of hours')
                ],
                'help' => $this->__('Here we can decide how long a user may edit his entry; input of hours'),
                'required' => false,
                'data' => $this->modVars['period'],
                'empty_data' => intval(''),
                'attr' => [
                    'title' => $this->__('Enter the period. Only digits are allowed.')
                ],'max_length' => 255,
                'scale' => 0
            ])
            ->add('simplecaptcha', 'Symfony\Component\Form\Extension\Core\Type\CheckboxType', [
                'label' => $this->__('Simplecaptcha') . ':',
                'required' => false,
                'data' => (bool)$this->modVars['simplecaptcha'],
                'attr' => [
                    'title' => $this->__('The simplecaptcha option.')
                ],
            ])
        ;
    }

    /**
     * Adds fields for moderation fields.
     *
     * @param FormBuilderInterface $builder The form builder
     * @param array                $options The options
     */
    public function addModerationFields(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('moderationGroupForEntries', 'Symfony\Bridge\Doctrine\Form\Type\EntityType', [
                'label' => $this->__('Moderation group for entries') . ':',
                'label_attr' => [
                    'class' => 'tooltips',
                    'title' => $this->__('Used to determine moderator user accounts for sending email notifications.')
                ],
                'help' => $this->__('Used to determine moderator user accounts for sending email notifications.'),
                'data' => $this->modVars['moderationGroupForEntries'],
                'attr' => [
                    'title' => $this->__('Choose the moderation group for entries.')
                ],'max_length' => 255,
                // Zikula core should provide a form type for this to hide entity details
                'class' => 'ZikulaGroupsModule:GroupEntity',
                'choice_label' => 'name',
                'choice_value' => 'gid'
            ])
        ;
    }

    /**
     * Adds fields for listviews fields.
     *
     * @param FormBuilderInterface $builder The form builder
     * @param array                $options The options
     */
    public function addListviewsFields(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('entryEntriesPerPage', 'Symfony\Component\Form\Extension\Core\Type\IntegerType', [
                'label' => $this->__('Entry entries per page') . ':',
                'label_attr' => [
                    'class' => 'tooltips',
                    'title' => $this->__('The amount of entries shown per page')
                ],
                'help' => $this->__('The amount of entries shown per page'),
                'required' => false,
                'data' => $this->modVars['entryEntriesPerPage'],
                'empty_data' => intval('10'),
                'attr' => [
                    'title' => $this->__('Enter the entry entries per page. Only digits are allowed.')
                ],'max_length' => 255,
                'scale' => 0
            ])
        ;
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'mueternizermodule_appsettings';
    }
}
