<?php
/**
 * Eternizer.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://www.webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.7.0 (http://modulestudio.de).
 */

namespace MU\EternizerModule\Entity\Factory;

use MU\EternizerModule\Entity\Factory\Base\EntryFactory as BaseEntryFactory;

/**
 * Factory class used to retrieve entity and repository instances.
 *
 * This is the concrete factory class for entry entities.
 */
class EntryFactory extends BaseEntryFactory
{
    // feel free to customise the manager
}
