<?php
/**
 * Eternizer.
 *
 * @copyright Michael Ueberschaer
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package Eternizer
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://www.webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.4 (http://modulestudio.de) at Wed Jan 04 16:43:44 CET 2012.
 */


/**
 * This is the Admin controller class providing navigation and interaction functionality.
 */
class Eternizer_Controller_Admin extends Eternizer_Controller_Base_Admin
{
	
	 /**
     * This method provides a generic item list overview.
     *
     * @param string  $ot           Treated object type.
     * @param string  $sort         Sorting field.
     * @param string  $sortdir      Sorting direction.
     * @param int     $pos          Current pager position.
     * @param int     $num          Amount of entries to display.
     * @param string  $tpl          Name of alternative template (for alternative display options, feeds and xml output)
     * @param boolean $raw          Optional way to display a template instead of fetching it (needed for standalone output)
     * @return mixed Output.
     */
    public function view($args)
    {
    	$sort = $this->request->getGet()->filter('sortdir', '', FILTER_SANITIZE_STRING);
    	    if ($sort == '') {
    	        $sortdir = ModUtil::getVar('Eternizer', 'order');
    	            if ($sortdir == 'descending') {
    		            $args['sortdir'] = 'desc';
    	            }
    	            else {
    		            $args['sortdir'] = 'asc';
    	            }
    	    }
    	
    	return parent::view($args);
    }
    
    /**
     * This method overrites the parent diplay function.
     *
     * @return mixed System Redirect.
     */
    public function display($args)
    {
        // DEBUG: permission check aspect starts
        $this->throwForbiddenUnless(SecurityUtil::checkPermission('Eternizer::', '::', ACCESS_ADMIN));
        // DEBUG: permission check aspect ends

        // return main template
        return System::redirect(ModUtil::url('Eternizer', 'admin', 'view'));
    }

    public function import()
    {

        // Create new Form reference
        $view = FormUtil::newForm($this->name, $this);

        // Execute form using supplied template and page event handler
        return $view->execute('admin/import.tpl', new Eternizer_Form_Handler_Admin_Base_Import());
    }
}
