<?php
/**
 * Eternizer.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link http://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace MU\EternizerModule\Container;

use MU\EternizerModule\Container\Base\AbstractHookContainer;

/**
 * Implementation class for hook container methods.
 */
class HookContainer extends AbstractHookContainer
{
    // feel free to add your own convenience methods here
}
