<?php
/**
 * Eternizer.
 *
 * @copyright Michael Ueberschaer
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package Eternizer
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://www.webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.4 (http://modulestudio.de) at Wed Jan 04 16:43:44 CET 2012.
 */

/**
 * Utility implementation class for view helper methods.
 */
class Eternizer_Util_View extends Eternizer_Util_Base_View
{
    /**
     * This method checks if user must edit this posting - creater of the issue
     */
    public static function getStateOfEditOfEntry($entryid, $kind = 1)
    {
        //get repository for Entries
        $repository = Eternizer_Util_Model::getEntryRepository();
        // get entry
        $entry = $repository->selectById($entryid);

        // get userid of user created this posting
        $createdUserId = $entry->getCreatedUserId();
        // get created Date
        $createdDate = $entry->getCreatedDate();
        $createdDate = $createdDate->getTimestamp();

        // get the actual time
        $actualTime = DateUtil::getDatetime();
        // get modvar editTime
        $editTime = ModUtil::getVar('Eternizer', 'period');

        $diffTime = DateUtil::getDatetimeDiff($createdDate, $actualTime);
        $diffTimeHours = $diffTime['d'] * 24 + $diffTime['h'];

        if (UserUtil::isLoggedIn()== true) {
            $userid = UserUtil::getVar('uid');
        } else {
            $out = '';
        }

        if ($createdUserId == $userid && ($diffTimeHours < $editTime) ) {
            if ($kind == 1) {
                $serviceManager = ServiceUtil::getManager();
                // generate an auth key to use in urls
                $csrftoken = SecurityUtil::generateCsrfToken($serviceManager, true);
                $url = ModUtil::url('Eternizer', 'user', 'edit', array('ot' => 'entry', 'id' => $entryid, 'token' => $csrftoken));
                $title = __('You have permissions to edit this issue!');
                $out = "<a title='{$title}' id='eternizer-user-entry-edit-creater' href='{$url}'>
                <img src='/images/icons/extrasmall/xedit.png' />
                </a>";
            } else {
                $out = true;

            }
        } else {
            if ($kind == 1) {
            $out = '';
            } else {
                $out = false;
            }
        }

        return $out;
    }
}
