<?php
/**
 * Eternizer.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://www.webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.7.0 (http://modulestudio.de).
 */

namespace MU\EternizerModule\Api\Base;

use ModUtil;
use UserUtil;
use Zikula\Core\Api\AbstractApi;
use Zikula_View;
use Zikula_View_Theme;

/**
 * Cache api base class.
 */
class CacheApi extends AbstractApi
{
    /**
     * Clear cache for given item. Can be called from other modules to clear an item cache.
     *
     * @param $args['ot']   the treated object type
     * @param $args['item'] the actual object
     */
    public function clearItemCache(array $args = array())
    {
        if (!isset($args['ot']) || !isset($args['item'])) {
            return;
        }
    
        $objectType = $args['ot'];
        $item = $args['item'];
    
        $controllerHelper = $this->get('mueternizermodule.controller_helper');
        $utilArgs = array('api' => 'cache', 'action' => 'clearItemCache');
        if (!in_array($objectType, $controllerHelper->getObjectTypes('controllerAction', $utilArgs))) {
            return;
        }
    
        if ($item && !is_array($item) && !is_object($item)) {
            $item = ModUtil::apiFunc($this->name, 'selection', 'getEntity', array('ot' => $objectType, 'id' => $item, 'useJoins' => false, 'slimMode' => true));
        }
    
        if (!$item) {
            return;
        }
    
        $instanceId = $item->createCompositeIdentifier();
    
        $logger = $this->get('logger');
        $logger->info('{app}: User {user} caused clearing the cache for entity {entity} with id {id}.', array('app' => 'MUEternizerModule', 'user' => UserUtil::getVar('uname'), 'entity' => $objectType, 'id' => $instanceId));
    
        // Clear View_cache
        $cacheIds = array();
        $cacheIds[] = 'user_index';
        switch ($objectType) {
            case 'entry':
                $cacheIds[] = 'entry_index';
                $cacheIds[] = $objectType . '_view';
                $cacheIds[] = $objectType . '_display|' . $instanceId;
                
                
                break;
        }
    
        $view = Zikula_View::getInstance('MUEternizerModule');
        foreach ($cacheIds as $cacheId) {
            $view->clear_cache(null, $cacheId);
        }
    
    
        // Clear Theme_cache
        $cacheIds = array();
        $cacheIds[] = 'homepage'; // for homepage (can be assigned in the Settings module)
        $cacheIds[] = 'MUEternizerModule/user/index'; // index function
        switch ($objectType) {
            case 'entry':
                $cacheIdPrefix = 'MUEternizerModule/' . $objectType . '/';
                $cacheIds[] = $cacheIdPrefix . 'index'; // index function
                $cacheIds[] = $cacheIdPrefix . 'view/'; // view function (list views)
                $cacheIds[] = $cacheIdPrefix . 'display/' . $instanceId; // display function (detail views)
                
                
                break;
        }
        $theme = Zikula_View_Theme::getInstance();
        $theme->clear_cacheid_allthemes($cacheIds);
    }
}
