<?php
/**
 * Eternizer.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://www.webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.7.0 (http://modulestudio.de).
 */

namespace MU\EternizerModule\Api\Base;

use ModUtil;
use SecurityUtil;
use System;
use Zikula\Core\Api\AbstractApi;

/**
 * This is the User api helper class.
 */
class UserApi extends AbstractApi
{
    /**
     * Returns available user panel links.
     *
     * @return array Array of user links.
     */
    public function getLinks()
    {
        $links = array();
        $router = $this->get('router');
        $request = $this->get('request');

        if (SecurityUtil::checkPermission($this->name . '::', '::', ACCESS_ADMIN)) {
            $links[] = array('url' => $router->generate('mueternizermodule_admin_index'),
                             'text' => $this->__('Backend'),
                             'title' => $this->__('Switch to administration area.'),
                             'icon' => 'wrench');
        }

        $controllerHelper = $this->get('mueternizermodule.controller_helper');
        $utilArgs = array('api' => 'user', 'action' => 'getLinks');
        $allowedObjectTypes = $controllerHelper->getObjectTypes('api', $utilArgs);

        $currentType = $request->query->filter('type', 'entry', false, FILTER_SANITIZE_STRING);
        $currentLegacyType = $request->query->filter('lct', 'user', false, FILTER_SANITIZE_STRING);
        $permLevel = in_array('admin', array($currentType, $currentLegacyType)) ? ACCESS_ADMIN : ACCESS_READ;

        if (in_array('entry', $allowedObjectTypes)
            && SecurityUtil::checkPermission($this->name . ':Entry:', '::', $permLevel)) {
            $links[] = array('url' => $router->generate('mueternizermodule_entry_view', array('lct' => 'user')),
                             'text' => $this->__('Entries'),
                             'title' => $this->__('Entry list'));
        }

        return $links;
    }
}
