<?php
/**
 * Eternizer.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link http://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace MU\EternizerModule\Form\Type;

use MU\EternizerModule\Form\Type\Base\AbstractEntryType;

/**
 * Entry editing form type implementation class.
 */
class EntryType extends AbstractEntryType
{
    // feel free to extend the entry editing form type class here
}
