<?php
/**
 * Eternizer.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\EternizerModule\Form\Type;

use MU\EternizerModule\Form\Type\Base\AbstractEntryType;

use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;

/**
 * Entry editing form type implementation class.
 */
class EntryType extends AbstractEntryType
{
	/**
	 * Adds basic entity fields.
	 *
	 * @param FormBuilderInterface $builder The form builder
	 * @param array                $options The options
	 */
	public function addEntityFields(FormBuilderInterface $builder, array $options)
	{
    parent::addEntityFields($builder, $options);
    $builder->add('captcha', TextType::class, [
    		'label' => $this->__('Please solve this calculation') . ':',
    		'empty_data' => '',
    		'help' => $this->__('To prevent spam'),
    		'attr' => [
    				'maxlength' => 15,
    				'class' => '',
    				'title' => $this->__('Enter the correct number!')
    		],
    		'required' => false,
    ]);
    }
}
