<?php
/**
 * Eternizer.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://www.webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.7.0 (http://modulestudio.de).
 */

namespace MU\EternizerModule\Util;

use MU\EternizerModule\Util\Base\ModelUtil as BaseModelUtil;
use DataUtil;
use UserUtil;

/**
 * Utility implementation class for model helper methods.
 */
class ModelUtil extends BaseModelUtil
{
    // build the query to searching items by userid == loggedin user
    public static function getUserId()
    {
        // get userid of loggedin user
        if (UserUtil::isLoggedIn() === true) {
            $userid = UserUtil::getVar('uid');
        }
        else {
            $userid = 0;
        }
        if ($userid != 0) {
            // build where clause
            $where = 'tbl.createdUserId = \'' . DataUtil::formatForStore($userid) . '\'';
        }
        else {
            $where = '';
        }

        return $where;

    }

    //build the where clause for allowed entries
    public static function entryAllowed()
    {
        $where = 'tbl.obj_status = \'' . DataUtil::formatForStore('A') . '\'';

        return $where;
    }
}
