<?php
/**
 * Eternizer.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://www.webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.7.0 (http://modulestudio.de).
 */

namespace MU\EternizerModule\Util;

use MU\EternizerModule\Util\Base\WorkflowUtil as BaseWorkflowUtil;

/**
 * Utility implementation class for workflow helper methods.
 */
class WorkflowUtil extends BaseWorkflowUtil
{
    // feel free to add your own convenience methods here
}
