services:
    # Form types
    
    mu_eternizer_module.form.type.entryquicknav:
        class: MU\EternizerModule\Form\Type\QuickNavigation\EntryQuickNavType
        arguments: ["@translator.default", "@request_stack", "@mu_eternizer_module.listentries_helper"]
        tags:
            - { name: form.type }
    
    mu_eternizer_module.form.handler.entry:
        class: MU\EternizerModule\Form\Handler\Entry\EditHandler
        arguments: ["@service_container", "@translator.default", "@request_stack", "@router"]
        tags:
            - { name: form.type }
    
    mu_eternizer_module.form.type.entry:
        class: MU\EternizerModule\Form\Type\EntryType
        arguments: ["@translator.default", "@mu_eternizer_module.entry_factory", "@mu_eternizer_module.listentries_helper"]
        tags:
            - { name: form.type }
    
    mu_eternizer_module.form.type.deleteentity:
        class: MU\EternizerModule\Form\DeleteEntityType
        arguments: ["@translator.default"]
        tags:
            - { name: form.type }
    
    mu_eternizer_module.form.type.block.itemlist:
        class: MU\EternizerModule\Block\Form\Type\ItemListBlockType
        arguments: ["@translator.default"]
        tags:
            - { name: form.type }
    
    mu_eternizer_module.form.type.entryfinder:
        class: MU\EternizerModule\Form\Type\Finder\EntryFinderType
        arguments: ["@translator.default"]
        tags:
            - { name: form.type }
    
    mu_eternizer_module.form.type.appsettings:
        class: MU\EternizerModule\Form\AppSettingsType
        arguments: ["@translator.default", "@zikula_extensions_module.api.variable", "@zikula_groups_module.group_repository"]
        tags:
            - { name: form.type }
