services:
    # Custom validators
    mu_eternizer_module.validator.list_entry.validator:
        class: MU\EternizerModule\Validator\Constraints\ListEntryValidator
        arguments:
            - "@translator.default"
            - "@mu_eternizer_module.listentries_helper"
        tags:
            - { name: validator.constraint_validator, alias: mu_eternizer_module.validator.list_entry.validator }
