<?php
/**
 * Eternizer.
 *
 * @copyright Michael Ueberschaer
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package Eternizer
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://www.webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.4 (http://modulestudio.de) at Sat Dec 31 13:59:03 CET 2011.
 */

/**
 * Utility implementation class for controller helper methods.
 */
class Eternizer_Util_Controller extends Eternizer_Util_Base_Controller
{
    /**
     * Get list of form positions.
     */
    public function getFormPositions()
    {
        $dom = ZLanguage::getModuleDomain('Eternizer');
        $position = array();
        $position[] = array('value' => 'above',    'text' => __('above', $dom),          'icon' => 'redled.png');
        $position[] = array('value' => 'below',    'text' => __('below', $dom),         'icon' => 'yellowled.png');
        $position[] = array('value' => 'menu',     'text' => __('menue', $dom),           'icon' => 'greenled.png');
        return $position;
    }
    
    /**
     * Get list of form positions.
     */
    public function getKindOfModeration()
    {
        $dom = ZLanguage::getModuleDomain('Eternizer');
        $moderation = array();
        $moderation[] = array('value' => 'all',    'text' => __('all', $dom),          'icon' => 'redled.png');
        $moderation[] = array('value' => 'guests',    'text' => __('guests', $dom),         'icon' => 'yellowled.png');
        $moderation[] = array('value' => 'users',     'text' => __('registered users', $dom),           'icon' => 'greenled.png');
        return $moderation;
    }
}
