<?php
/**
 * Eternizer.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\EternizerModule\Helper;

use MU\EternizerModule\Helper\Base\AbstractControllerHelper;
use Zikula\UsersModule\Api\ApiInterface\CurrentUserApiInterface;

/**
 * Helper implementation class for controller layer methods.
 */
class ControllerHelper extends AbstractControllerHelper
{
    /**
     * @var CurrentUserApiInterface
     */
    protected $currentUserApi;

    /**
     * @param int     $entryid
     * @param int     $createdUserId
     * @param int     $createdDate
     * @param int     $kind
     * @return string|boolean
     */
    public function EditEntry($entryid, $createdBy, $createdDate, $kind = 1)
    {
        $userid = $this->currentUserApi->get('uid');

        // get the actual time
        $actualTime = new \DateTime();
        // get modvar editTime
        $editTime = $this->variableApi->get('MUEternizerModule', 'period');

        $diffTime = $actualTime->diff($createdDate);
        $diffTimeHours = $diffTime->d * 24 + $diffTime->h;

        if (false == $this->currentUserApi->isLoggedIn()) {
            $out = '';
        }

        if ($createdBy == $userid && $diffTimeHours < $editTime) {
            if ($kind == 1) {
                // TODO
                /*
                $serviceManager = \ServiceUtil::getManager();
                // generate an auth key to use in urls
                $csrftoken = \SecurityUtil::generateCsrfToken($serviceManager, true);

                $url = \ModUtil::url('MUEternizerModule', 'entry', 'edit', array('id' => $entryid));
                $title = __('You have permissions to edit this issue!');
                $out = "
                    <a title=\"{$title}\" id=\"eternizer-user-entry-edit-creater\" href=\"{$url}\">
                    <i class=\"fa fa-pencil-square-o\" aria-hidden=\"true\"></i>
                    </a>
                ";*/
                $out = '';
            } else {
                $out = true;
        
            }
        } else {
            if ($kind == 1) {
                $out = '';
            } else {
                $out = false;
            }
        }

        return $out;
    }

    public function setCurrentUserApi(CurrentUserApiInterface $currentUserApi)
    {
        $this->currentUserApi = $currentUserApi;
    }
}
