<?php
/**
 * Eternizer.
 *
 * @copyright Michael Ueberschaer
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package Eternizer
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://www.webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.4 (http://modulestudio.de) at Tue Jan 03 13:01:47 CET 2012.
 */

/**
 * This is the Ajax controller class providing navigation and interaction functionality.
 */
class Eternizer_Controller_Ajax extends Eternizer_Controller_Base_Ajax
{
    // feel free to add your own controller methods here
}
