<?php
/**
 * Eternizer.
 *
 * @copyright Michael Ueberschaer
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package Eternizer
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://www.webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.4 (http://modulestudio.de) at Sat Dec 31 13:59:03 CET 2011.
 */


/**
 * This is the User controller class providing navigation and interaction functionality.
 */
class Eternizer_Controller_User extends Eternizer_Controller_Base_User
{
	    /**
     * This method provides the handling of
     * the formposition
     * the editing of entries and
     * the order of entries
     *
     * @param string  $formposition		position of the create form
     * @param int  $userid              the userid of loggedin users
     * @param string  $args['sortdir']  Sorting direction
     * 
     * return the parent function
     * 
     */
    public function view($args)
    {
    	// We rule the position of the form
    	$formposition = ModUtil::getVar($this->name, 'formposition');
    	
    	//We check the userid for ruling the edit button
    	$userid = UserUtil::getVar('uid');

    	// We assign to the template
    	$this->view->assign('formposition', $formposition);
    	$this->view->assign('userid', $userid);
    	
    	$order = ModUtil::getVar($this->name, 'order');
    	if ($order == 'descending') {
    		$args['sortdir'] = 'desc';
    	}
    	else {
    		$args['sortdir'] = 'asc';
    	}
    	
    	return parent::view($args);
    }
}
