<?php
/**
 * Eternizer.
 *
 * @copyright Michael Ueberschaer
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package Eternizer
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://www.webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.4 (http://modulestudio.de) at Sat Dec 31 13:59:03 CET 2011.
 */


/**
 * This is the User controller class providing navigation and interaction functionality.
 */
class Eternizer_Controller_User extends Eternizer_Controller_Base_User
{
	    /**
     * This method provides a generic item list overview.
     *
     * @param string  $ot           Treated object type.
     * @param string  $sort         Sorting field.
     * @param string  $sortdir      Sorting direction.
     * @param int     $pos          Current pager position.
     * @param int     $num          Amount of entries to display.
     * @param string  $tpl          Name of alternative template (for alternative display options, feeds and xml output)
     * @param boolean $raw          Optional way to display a template instead of fetching it (needed for standalone output)
     * @return mixed Output.
     */
    public function view($args)
    {
    	// We rule the position of the form
    	$formposition = ModUtil::getVar($this->name, 'formposition');

    	// We assign to the template
    	$this->view->assign('formposition', $formposition);
    	
    	$order = ModUtil::getVar($this->name, 'order');
    	if ($order == 'descending') {
    		$args['sortdir'] = 'desc';
    	}
    	else {
    		$args['sortdir'] = 'asc';
    	}
    	
    	return parent::view($args);
    }
}
