
<?php
/**
 * Eternizer.
 *
 * @copyright Michael Ueberschaer
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package Eternizer
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://www.webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.4 (http://modulestudio.de) at Sat Dec 31 13:59:03 CET 2011.
 */


/**
 * Configuration handler implementation class
 */
class Eternizer_Form_Handler_Admin_Config extends Eternizer_Form_Handler_Admin_Base_Config
{
    /**
     * Method stub for own additions in subclasses.
     */
    protected function initializeAdditions()
    {
    	$position = Eternizer_Util_Controller::getFormPositions();
    	$moderation = Eternizer_Util_Controller::getKindOfModeration();
    	
    	$config = $this->view->get_template_vars('config');
     	$config['formpositionItems'] = $position;
     	$config['moderateItems'] = $moderation;
     	$this->view->assign('config', $config);
    }
}
