<?php
/**
 * Eternizer.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://www.webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace MU\EternizerModule\Twig;

use MU\EternizerModule\Twig\Base\AbstractTwigExtension;
use Symfony\Component\HttpKernel\Controller\ControllerReference;

use ServiceUtil;

/**
 * Twig extension implementation class.
 */
class TwigExtension extends AbstractTwigExtension
{	
    /**
     * Returns a list of custom Twig functions.
     *
     * @return array
     */
    public function getFunctions()
    {
    	$functions = parent::getFunctions();
    	$functions[] = new \Twig_SimpleFunction('mueternizermodule_showEditForm', [$this, 'showEditForm'], ['is_safe' => ['html']]);
    	$functions[] = new \Twig_SimpleFunction('mueternizermodule_editEntry', [$this, 'editEntry']);
    	$functions[] = new \Twig_SimpleFunction('mueternizermodule_simpleCaptcha', [$this, 'simpleCaptcha'], ['is_safe' => ['html']]);
    	
    	return $functions;
    }
    
    public function showEditForm()
    {
    	$request = \ServiceUtil::get('request_stack')->getMasterRequest();
    	$request->attributes->set('_zkModule', 'MUEternizerModule');
    
    	$fragmentHandler = \ServiceUtil::get('fragment.handler');
    
    	$ref = new ControllerReference('MUEternizerModule:Entry:edit');
    
    	return $fragmentHandler->render($ref, 'inline', []);
    }
    
    /**
     * The mueternizermodule_editEntry function checks if an item is in edit period.
     *
     * @return string The output of the plugin
     */
    public function editEntry($entryid, $createdUserId, $createdDate,  $kind = 1)
    {
    	$out = $this->controllerHelper->EditEntry($entryid, $createdUserId, $createdDate,  $kind = 1);

        return $out;
    }
    
    /**
     * The mueternizermodule_simpleCaptcha function adds a simplecaptcha image to a form.
     *
     * Example:
     *     {{ mueternizermodule_simpleCaptcha(font='quickhand', size=14, bgColour='ffffff', fgColour='000000') }}
     *
     * @param string $font     Name of font to use (arial, freesans, quickhand, vera)
     * @param int    $size     Font size
     * @param string $bgColour Background colour (hex code without the # char)
     * @param string $fgColour Foreground colour (hex code without the # char)
     *
     * @return string The image markup
     */
    public function simpleCaptcha($font = 'quickhand', $size = 14, $bgColour = 'ffffff', $fgColour = '000000')
    {
    	return $this->captchaHelper->createCaptcha($font, $size, $bgColour, $fgColour);
    }
}
