<?php
/**
 * Eternizer.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://www.webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace MU\EternizerModule\Entity\Repository;

use MU\EternizerModule\Entity\Repository\Base\AbstractEntryRepository;

/**
 * Repository class used to implement own convenience methods for performing certain DQL queries.
 *
 * This is the concrete repository class for entry entities.
 */
class EntryRepository extends AbstractEntryRepository
{
    /**
     * @var string The default sorting field/expression
     */
    protected $defaultSortingField = 'createdDate';
}
