modules/mUEternizer/Resources/views/Entry/index.tpl: config/templates/MUEternizerModule/Entry/index.tpl
modules/mUEternizer/Resources/views/Entry/view.tpl: config/templates/MUEternizerModule/Entry/view.tpl
modules/mUEternizer/Resources/views/Entry/view_quickNav.tpl: config/templates/MUEternizerModule/Entry/view_quickNav.tpl
modules/mUEternizer/Resources/views/Entry/view.csv.tpl: config/templates/MUEternizerModule/Entry/view.csv.tpl
modules/mUEternizer/Resources/views/Entry/view.rss.tpl: config/templates/MUEternizerModule/Entry/view.rss.tpl
modules/mUEternizer/Resources/views/Entry/view.atom.tpl: config/templates/MUEternizerModule/Entry/view.atom.tpl
modules/mUEternizer/Resources/views/Entry/view.xml.tpl: config/templates/MUEternizerModule/Entry/view.xml.tpl
modules/mUEternizer/Resources/views/Entry/display.xml.tpl: config/templates/MUEternizerModule/Entry/display.xml.tpl
modules/mUEternizer/Resources/views/Entry/include.xml.tpl: config/templates/MUEternizerModule/Entry/include.xml.tpl
modules/mUEternizer/Resources/views/Entry/view.json.tpl: config/templates/MUEternizerModule/Entry/view.json.tpl
modules/mUEternizer/Resources/views/Entry/display.json.tpl: config/templates/MUEternizerModule/Entry/display.json.tpl
modules/mUEternizer/Resources/views/Entry/display.tpl: config/templates/MUEternizerModule/Entry/display.tpl
modules/mUEternizer/Resources/views/Entry/delete.tpl: config/templates/MUEternizerModule/Entry/delete.tpl
modules/mUEternizer/Resources/views/Admin/header.tpl: config/templates/MUEternizerModule/Admin/header.tpl
modules/mUEternizer/Resources/views/Admin/footer.tpl: config/templates/MUEternizerModule/Admin/footer.tpl
modules/mUEternizer/Resources/views/User/header.tpl: config/templates/MUEternizerModule/User/header.tpl
modules/mUEternizer/Resources/views/User/footer.tpl: config/templates/MUEternizerModule/User/footer.tpl
modules/mUEternizer/Resources/views/Entry/edit.tpl: config/templates/MUEternizerModule/Entry/edit.tpl
modules/mUEternizer/Resources/views/Entry/inlineRedirectHandler.tpl: config/templates/MUEternizerModule/Entry/inlineRedirectHandler.tpl
modules/mUEternizer/Resources/views/Helper/include_standardfields_display.tpl: config/templates/MUEternizerModule/Helper/include_standardfields_display.tpl
modules/mUEternizer/Resources/views/Helper/include_standardfields_edit.tpl: config/templates/MUEternizerModule/Helper/include_standardfields_edit.tpl
modules/mUEternizer/Resources/views/include_filterSyntaxDialog.tpl: config/templates/MUEternizerModule/include_filterSyntaxDialog.tpl
modules/mUEternizer/Resources/views/Admin/config.tpl: config/templates/MUEternizerModule/Admin/config.tpl
modules/mUEternizer/Resources/views/include_pdfheader.tpl: config/templates/MUEternizerModule/include_pdfheader.tpl
