<?php
/**
 * Eternizer.
 *
 * @copyright Michael Ueberschaer
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package Eternizer
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://www.webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.4 (http://modulestudio.de) at Wed Jan 04 16:43:44 CET 2012.
 */

namespace MU\EternizerModule\Util\Base;

use Zikula_AbstractBase;

/**
 * Utility base class for settings helper methods.
 */
class SettingsUtil extends Zikula_AbstractBase
{
    // feel free to add your own convenience methods here
}
