<?php
/**
 * Eternizer.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\EternizerModule\HookSubscriber;

use MU\EternizerModule\HookSubscriber\Base\AbstractEntryFilterHooksSubscriber;

/**
 * Implementation class for filter hooks subscriber.
 */
class EntryFilterHooksSubscriber extends AbstractEntryFilterHooksSubscriber
{
    // feel free to add your own convenience methods here
}
