<?php
/**
 * Eternizer.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://www.webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace MU\EternizerModule\Container\Base;

use Symfony\Component\Routing\RouterInterface;
use UserUtil;
use Zikula\Common\Translator\TranslatorInterface;
use Zikula\Common\Translator\TranslatorTrait;
use Zikula\Core\Doctrine\EntityAccess;
use Zikula\Core\LinkContainer\LinkContainerInterface;
use Zikula\PermissionsModule\Api\PermissionApi;
use Zikula\ExtensionsModule\Api\VariableApi;
use Zikula\UsersModule\Api\CurrentUserApi;
use MU\EternizerModule\Entity\EntryEntity;
use MU\EternizerModule\Helper\ControllerHelper;

/**
 * This is the link container service implementation class.
 */
abstract class AbstractLinkContainer implements LinkContainerInterface
{
    use TranslatorTrait;

    /**
     * @var RouterInterface
     */
    protected $router;

    /**
     * @var PermissionApi
     */
    protected $permissionApi;

    /**
     * @var ControllerHelper
     */
    protected $controllerHelper;

    /**
     * @var VariableApi
     */
    protected $variableApi;

    /**
     * @var CurrentUserApi
     */
    private $currentUserApi;

    /**
     * Constructor.
     * Initialises member vars.
     *
     * @param TranslatorInterface $translator       Translator service instance
     * @param Routerinterface     $router           Router service instance
     * @param PermissionApi       $permissionApi    PermissionApi service instance
     * @param ControllerHelper    $controllerHelper ControllerHelper service instance
     * @param VariableApi         $variableApi      VariableApi service instance
     * @param CurrentUserApi      $currentUserApi   CurrentUserApi service instance
     */
    public function __construct(TranslatorInterface $translator, RouterInterface $router, PermissionApi $permissionApi, ControllerHelper $controllerHelper, VariableApi $variableApi, CurrentUserApi $currentUserApi)
    {
        $this->setTranslator($translator);
        $this->router = $router;
        $this->permissionApi = $permissionApi;
        $this->controllerHelper = $controllerHelper;
        $this->variableApi = $variableApi;
        $this->currentUserApi = $currentUserApi;
    }

    /**
     * Sets the translator.
     *
     * @param TranslatorInterface $translator Translator service instance
     */
    public function setTranslator(/*TranslatorInterface */$translator)
    {
        $this->translator = $translator;
    }

    /**
     * Returns available header links.
     *
     * @param string $type The type to collect links for
     *
     * @return array Array of header links
     */
    public function getLinks($type = LinkContainerInterface::TYPE_ADMIN)
    {
        $utilArgs = ['api' => 'linkContainer', 'action' => 'getLinks'];
        $allowedObjectTypes = $this->controllerHelper->getObjectTypes('api', $utilArgs);

        $permLevel = LinkContainerInterface::TYPE_ADMIN == $type ? ACCESS_ADMIN : ACCESS_READ;

        // Create an array of links to return
        $links = [];

        if (LinkContainerInterface::TYPE_ACCOUNT == $type) {
            $useAccountPage = $this->variableApi->get('MUEternizerModule', 'useAccountPage', true);
            if ($useAccountPage === false) {
                return $links;
            }

            $userName = isset($args['uname']) ? $args['uname'] : $this->currentUserApi->get('uname');
            // does this user exist?
            if (UserUtil::getIdFromName($userName) === false) {
                // user does not exist
                return $links;
            }

            if (!$this->permissionApi->hasPermission($this->getBundleName() . '::', '::', ACCESS_OVERVIEW)) {
                return $links;
            }

            if ($this->permissionApi->hasPermission($this->getBundleName() . '::', '::', ACCESS_ADMIN)) {
                $links[] = [
                    'url' => $this->router->generate('mueternizermodule_admin_index'),
                    'text' => $this->__('Eternizer Backend'),
                    'icon' => 'wrench'
                ];
            }

            return $links;
        }

        
        if (LinkContainerInterface::TYPE_ADMIN == $type) {
            if ($this->permissionApi->hasPermission($this->getBundleName() . '::', '::', ACCESS_READ)) {
                $links[] = [
                    'url' => $this->router->generate('mueternizermodule_user_index'),
                    'text' => $this->__('Frontend'),
                    'title' => $this->__('Switch to user area.'),
                    'icon' => 'home'
                ];
            }
            
            if (in_array('entry', $allowedObjectTypes)
                && $this->permissionApi->hasPermission($this->getBundleName() . ':Entry:', '::', $permLevel)) {
                $links[] = [
                    'url' => $this->router->generate('mueternizermodule_entry_adminview'),
                     'text' => $this->__('Entries'),
                     'title' => $this->__('Entry list')
                 ];
            }
            if ($this->permissionApi->hasPermission($this->getBundleName() . '::', '::', ACCESS_ADMIN)) {
                $links[] = [
                    'url' => $this->router->generate('mueternizermodule_config_config'),
                    'text' => $this->__('Configuration'),
                    'title' => $this->__('Manage settings for this application'),
                    'icon' => 'wrench'
                ];
            }
        }
        if (LinkContainerInterface::TYPE_USER == $type) {
            if ($this->permissionApi->hasPermission($this->getBundleName() . '::', '::', ACCESS_ADMIN)) {
                $links[] = [
                    'url' => $this->router->generate('mueternizermodule_admin_index'),
                    'text' => $this->__('Backend'),
                    'title' => $this->__('Switch to administration area.'),
                    'icon' => 'wrench'
                ];
            }
            
            if (in_array('entry', $allowedObjectTypes)
                && $this->permissionApi->hasPermission($this->getBundleName() . ':Entry:', '::', $permLevel)) {
                $links[] = [
                    'url' => $this->router->generate('mueternizermodule_entry_view'),
                     'text' => $this->__('Entries'),
                     'title' => $this->__('Entry list')
                 ];
            }
            if ($this->permissionApi->hasPermission($this->getBundleName() . '::', '::', ACCESS_ADMIN)) {
                $links[] = [
                    'url' => $this->router->generate('mueternizermodule_config_config'),
                    'text' => $this->__('Configuration'),
                    'title' => $this->__('Manage settings for this application'),
                    'icon' => 'wrench'
                ];
            }
        }

        return $links;
    }

    /**
     * Returns action links for a given entity.
     *
     * @param EntityAccess $entity  The entity
     * @param string       $area    The context area name (e.g. admin or nothing for user)
     * @param string       $context The context page name (e.g. view, display, edit, delete)
     *
     * @return array Array of action links
     */
    public function getActionLinks(EntityAccess $entity, $area = '', $context = 'view')
    {
        // Create an array of links to return
        $links = [];

        
        $currentLegacyControllerType = $area != '' ? $area : 'user';
        $currentFunc = $context;
        
        if ($entity instanceof EntryEntity) {
            $component = 'MUEternizerModule:Entry:';
            $instance = $entity['id'] . '::';
        
        if ($currentLegacyControllerType == 'admin') {
            if (in_array($currentFunc, ['index', 'view'])) {
                $links[] = [
                    'url' => $this->router->generate('mueternizermodule_entry_display', ['id' => $entity['id']]),
                    'icon' => 'search-plus',
                    'linkTitle' => $this->__('Open preview page'),
                    'linkText' => $this->__('Preview')
                ];
                $links[] = [
                    'url' => $this->router->generate('mueternizermodule_entry_admindisplay', ['id' => $entity['id']]),
                    'icon' => 'eye',
                    'linkTitle' => str_replace('"', '', $entity->getTitleFromDisplayPattern()),
                    'linkText' => $this->__('Details')
                ];
            }
            if (in_array($currentFunc, ['index', 'view', 'display'])) {
                if ($this->permissionApi->hasPermission($component, $instance, ACCESS_EDIT)) {
                    $links[] = [
                        'url' => $this->router->generate('mueternizermodule_entry_adminedit', ['id' => $entity['id']]),
                        'icon' => 'pencil-square-o',
                        'linkTitle' => $this->__('Edit'),
                        'linkText' => $this->__('Edit')
                    ];
                    $links[] = [
                        'url' => $this->router->generate('mueternizermodule_entry_adminedit', ['astemplate' => $entity['id']]),
                        'icon' => 'files-o',
                        'linkTitle' => $this->__('Reuse for new item'),
                        'linkText' => $this->__('Reuse')
                    ];
                }
                if ($this->permissionApi->hasPermission($component, $instance, ACCESS_DELETE)) {
                    $links[] = [
                        'url' => $this->router->generate('mueternizermodule_entry_admindelete', ['id' => $entity['id']]),
                        'icon' => 'trash-o',
                        'linkTitle' => $this->__('Delete'),
                        'linkText' => $this->__('Delete')
                    ];
                }
            }
            if ($currentFunc == 'display') {
                $links[] = [
                    'url' => $this->router->generate('mueternizermodule_entry_adminview'),
                    'icon' => 'reply',
                    'linkTitle' => $this->__('Back to overview'),
                    'linkText' => $this->__('Back to overview')
                ];
            }
        }
        if ($currentLegacyControllerType == 'user') {
            if (in_array($currentFunc, ['index', 'view'])) {
                $links[] = [
                    'url' => $this->router->generate('mueternizermodule_entry_display', ['id' => $entity['id']]),
                    'icon' => 'eye',
                    'linkTitle' => str_replace('"', '', $entity->getTitleFromDisplayPattern()),
                    'linkText' => $this->__('Details')
                ];
            }
            if (in_array($currentFunc, ['index', 'view', 'display'])) {
                if ($this->permissionApi->hasPermission($component, $instance, ACCESS_EDIT)) {
                    $links[] = [
                        'url' => $this->router->generate('mueternizermodule_entry_edit', ['id' => $entity['id']]),
                        'icon' => 'pencil-square-o',
                        'linkTitle' => $this->__('Edit'),
                        'linkText' => $this->__('Edit')
                    ];
                    $links[] = [
                        'url' => $this->router->generate('mueternizermodule_entry_edit', ['astemplate' => $entity['id']]),
                        'icon' => 'files-o',
                        'linkTitle' => $this->__('Reuse for new item'),
                        'linkText' => $this->__('Reuse')
                    ];
                }
                if ($this->permissionApi->hasPermission($component, $instance, ACCESS_DELETE)) {
                    $links[] = [
                        'url' => $this->router->generate('mueternizermodule_entry_delete', ['id' => $entity['id']]),
                        'icon' => 'trash-o',
                        'linkTitle' => $this->__('Delete'),
                        'linkText' => $this->__('Delete')
                    ];
                }
            }
            if ($currentFunc == 'display') {
                $links[] = [
                    'url' => $this->router->generate('mueternizermodule_entry_view'),
                    'icon' => 'reply',
                    'linkTitle' => $this->__('Back to overview'),
                    'linkText' => $this->__('Back to overview')
                ];
            }
        }
        }

        return $links;
    }

    /**
     * Returns the name of the providing bundle.
     *
     * @return string The bundle name
     */
    public function getBundleName()
    {
        return 'MUEternizerModule';
    }
}
