<?php
/**
 * Eternizer.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://www.webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.7.0 (http://modulestudio.de) at Sun Aug 30 13:45:20 CEST 2015.
 */

namespace MU\EternizerModule\Base;

use HookUtil;
use Zikula_AbstractVersion;
use Zikula\Component\HookDispatcher\ProviderBundle;
use Zikula\Component\HookDispatcher\SubscriberBundle;
use Zikula\Module\SearchModule\AbstractSearchable;

/**
 * Version information base class.
 */
class EternizerModuleVersion extends Zikula_AbstractVersion
{
    /**
     * Retrieves meta data information for this application.
     *
     * @return array List of meta data.
     */
    public function getMetaData()
    {
        $meta = array();
        // the current module version
        $meta['version']              = '1.2.0';
        // the displayed name of the module
        $meta['displayname']          = $this->__('Eternizer');
        // the module description
        $meta['description']          = $this->__('Eternizer - A guestbook module');
        //! url version of name, should be in lowercase without space
        $meta['url']                  = $this->__('eternizer');
        // core requirement
        $meta['core_min']             = '1.4.0'; // requires minimum 1.4.0 or later
        $meta['core_max']             = '1.4.99'; // not ready for 1.5.0 yet

        // define special capabilities of this module
        $meta['capabilities'] = array(
              HookUtil::SUBSCRIBER_CAPABLE => array('enabled' => true),
              AbstractSearchable::SEARCHABLE => array('class' => 'MU\EternizerModule\Helper\SearchHelper')
/*,
              HookUtil::PROVIDER_CAPABLE => array('enabled' => true), // TODO: see #15
*/
        );

        // permission schema
        $meta['securityschema'] = array(
            'MUEternizerModule::' => '::',
            'MUEternizerModule::Ajax' => '::',
            'MUEternizerModule:ItemListBlock:' => 'Block title::',
            'MUEternizerModule:Entry:' => 'Entry ID::',
        );
        // DEBUG: permission schema aspect ends


        return $meta;
    }

    /**
     * Define hook subscriber bundles.
     */
    protected function setupHookBundles()
    {
        
        $bundle = new SubscriberBundle($this->name, 'subscriber.mueternizermodule.ui_hooks.entries', 'ui_hooks', $this->__('mueternizermodule Entries Display Hooks'));
        
        // Display hook for view/display templates.
        $bundle->addEvent('display_view', 'mueternizermodule.ui_hooks.entries.display_view');
        // Display hook for create/edit forms.
        $bundle->addEvent('form_edit', 'mueternizermodule.ui_hooks.entries.form_edit');
        // Display hook for delete dialogues.
        $bundle->addEvent('form_delete', 'mueternizermodule.ui_hooks.entries.form_delete');
        // Validate input from an ui create/edit form.
        $bundle->addEvent('validate_edit', 'mueternizermodule.ui_hooks.entries.validate_edit');
        // Validate input from an ui create/edit form (generally not used).
        $bundle->addEvent('validate_delete', 'mueternizermodule.ui_hooks.entries.validate_delete');
        // Perform the final update actions for a ui create/edit form.
        $bundle->addEvent('process_edit', 'mueternizermodule.ui_hooks.entries.process_edit');
        // Perform the final delete actions for a ui form.
        $bundle->addEvent('process_delete', 'mueternizermodule.ui_hooks.entries.process_delete');
        $this->registerHookSubscriberBundle($bundle);

        $bundle = new SubscriberBundle($this->name, 'subscriber.mueternizermodule.filter_hooks.entries', 'filter_hooks', $this->__('mueternizermodule Entries Filter Hooks'));
        // A filter applied to the given area.
        $bundle->addEvent('filter', 'mueternizermodule.filter_hooks.entries.filter');
        $this->registerHookSubscriberBundle($bundle);

        
    }
}
