<?php
/**
 * Eternizer.
 *
 * @copyright Michael Ueberschaer
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package Eternizer
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://www.webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.4 (http://modulestudio.de) at Wed Jan 04 16:43:44 CET 2012.
 */

/**
 * This is the Search api helper class.
 */
class Eternizer_Api_Base_Search extends Zikula_AbstractApi
{
    /**
     * get available Search panel links
     *
     * @return array Array of admin links
     */
    public function getlinks()
    {
        $links = array();

        return $links;
    }
}
