<?php
/**
 * Eternizer.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://www.webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.7.0 (http://modulestudio.de).
 */

/**
 * MUEternizerModule entry needle information.
 *
 * @param none
 *
 * @return string with short usage description
 */
function MUEternizerModule_needleapi_entry_baseInfo()
{
    $info = [
        // module name
        'module'  => 'MUEternizerModule',
        // possible needles
        'info'    => 'ETERNIZER{ENTRIES|ENTRY-entryId}',
        // whether a reverse lookup is possible, needs MUEternizerModule_needleapi_entry_inspect() function
        'inspect' => false
    ];

    return $info;
}
