<?php
/**
 * Eternizer.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://www.webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

include_once 'Needles/Base/Abstractentry_info.php';

/**
 * MUEternizerModule entry needle information.
 *
 * @param none
 *
 * @return string with short usage description
 */
function MUEternizerModule_needleapi_entry_info()
{
    return MUEternizerModule_needleapi_entry_baseInfo();
}
