<?php
/**
 * Eternizer.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\EternizerModule\Form\Type\Base;

use Symfony\Component\Form\AbstractType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Zikula\Common\Translator\TranslatorInterface;
use Zikula\Common\Translator\TranslatorTrait;
use Zikula\GroupsModule\Constant as GroupsConstant;
use Zikula\GroupsModule\Entity\RepositoryInterface\GroupRepositoryInterface;

/**
 * Configuration form type base class.
 */
abstract class AbstractConfigType extends AbstractType
{
    use TranslatorTrait;

    /**
     * @var array
     */
    protected $moduleVars;

    /**
     * ConfigType constructor.
     *
     * @param TranslatorInterface      $translator      Translator service instance
     * @param object                   $moduleVars      Existing module vars
     * @param GroupRepositoryInterface $groupRepository GroupRepository service instance
     */
    public function __construct(
        TranslatorInterface $translator,
        $moduleVars,
        GroupRepositoryInterface $groupRepository
    ) {
        $this->setTranslator($translator);
        $this->moduleVars = $moduleVars;

        // prepare group selector values
        foreach (['moderationGroupForEntries'] as $groupFieldName) {
            $groupId = intval($this->moduleVars[$groupFieldName]);
            if ($groupId < 1) {
                // fallback to admin group
                $groupId = GroupsConstant::GROUP_ID_ADMIN;
            }
            $this->moduleVars[$groupFieldName] = $groupRepository->find($groupId);
        }
    }

    /**
     * Sets the translator.
     *
     * @param TranslatorInterface $translator Translator service instance
     */
    public function setTranslator(/*TranslatorInterface */$translator)
    {
        $this->translator = $translator;
    }

    /**
     * @inheritDoc
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $this->addVariablesFields($builder, $options);
        $this->addModerationFields($builder, $options);
        $this->addListViewsFields($builder, $options);
        $this->addIntegrationFields($builder, $options);

        $builder
            ->add('save', SubmitType::class, [
                'label' => $this->__('Update configuration'),
                'icon' => 'fa-check',
                'attr' => [
                    'class' => 'btn btn-success'
                ]
            ])
            ->add('cancel', SubmitType::class, [
                'label' => $this->__('Cancel'),
                'icon' => 'fa-times',
                'attr' => [
                    'class' => 'btn btn-default',
                    'formnovalidate' => 'formnovalidate'
                ]
            ])
        ;
    }

    /**
     * Adds fields for variables fields.
     *
     * @param FormBuilderInterface $builder The form builder
     * @param array                $options The options
     */
    public function addVariablesFields(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('mail', TextType::class, [
                'label' => $this->__('Mail') . ':',
                'required' => false,
                'data' => isset($this->moduleVars['mail']) ? $this->moduleVars['mail'] : '',
                'empty_data' => '',
                'attr' => [
                    'maxlength' => 255,
                    'title' => $this->__('Enter the mail.')
                ],
            ])
            ->add('order', ChoiceType::class, [
                'label' => $this->__('Order') . ':',
                'data' => isset($this->moduleVars['order']) ? $this->moduleVars['order'] : '',
                'empty_data' => '',
                'attr' => [
                    'title' => $this->__('Choose the order.')
                ],'choices' => [
                    $this->__('Descending') => 'descending',
                    $this->__('Ascending') => 'ascending'
                ],
                'choices_as_values' => true,
                'multiple' => false
            ])
            ->add('moderate', ChoiceType::class, [
                'label' => $this->__('Moderate') . ':',
                'data' => isset($this->moduleVars['moderate']) ? $this->moduleVars['moderate'] : '',
                'empty_data' => '',
                'attr' => [
                    'title' => $this->__('Choose the moderate.')
                ],'choices' => [
                    $this->__('Nothing') => 'nothing',
                    $this->__('Guests') => 'guests',
                    $this->__('All') => 'all'
                ],
                'choices_as_values' => true,
                'multiple' => false
            ])
            ->add('formposition', ChoiceType::class, [
                'label' => $this->__('Formposition') . ':',
                'data' => isset($this->moduleVars['formposition']) ? $this->moduleVars['formposition'] : '',
                'empty_data' => '',
                'attr' => [
                    'title' => $this->__('Choose the formposition.')
                ],'choices' => [
                    $this->__('Above') => 'above',
                    $this->__('Below') => 'below',
                    $this->__('Menue') => 'menue'
                ],
                'choices_as_values' => true,
                'multiple' => false
            ])
            ->add('ipsave', CheckboxType::class, [
                'label' => $this->__('Ipsave') . ':',
                'required' => false,
                'data' => (bool)(isset($this->moduleVars['ipsave']) ? $this->moduleVars['ipsave'] : false),
                'attr' => [
                    'title' => $this->__('The ipsave option.')
                ],
            ])
            ->add('editentries', CheckboxType::class, [
                'label' => $this->__('Editentries') . ':',
                'required' => false,
                'data' => (bool)(isset($this->moduleVars['editentries']) ? $this->moduleVars['editentries'] : false),
                'attr' => [
                    'title' => $this->__('The editentries option.')
                ],
            ])
            ->add('period', IntegerType::class, [
                'label' => $this->__('Period') . ':',
                'label_attr' => [
                    'class' => 'tooltips',
                    'title' => $this->__('Here we can decide how long a user may edit his entry; input of hours')
                ],
                'help' => $this->__('Here we can decide how long a user may edit his entry; input of hours'),
                'required' => false,
                'data' => isset($this->moduleVars['period']) ? intval($this->moduleVars['period']) : intval(),
                'empty_data' => intval(''),
                'attr' => [
                    'maxlength' => 255,
                    'title' => $this->__('Enter the period.') . ' ' . $this->__('Only digits are allowed.')
                ],'scale' => 0
            ])
            ->add('simplecaptcha', CheckboxType::class, [
                'label' => $this->__('Simplecaptcha') . ':',
                'required' => false,
                'data' => (bool)(isset($this->moduleVars['simplecaptcha']) ? $this->moduleVars['simplecaptcha'] : false),
                'attr' => [
                    'title' => $this->__('The simplecaptcha option.')
                ],
            ])
        ;
    }

    /**
     * Adds fields for moderation fields.
     *
     * @param FormBuilderInterface $builder The form builder
     * @param array                $options The options
     */
    public function addModerationFields(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('moderationGroupForEntries', EntityType::class, [
                'label' => $this->__('Moderation group for entries') . ':',
                'label_attr' => [
                    'class' => 'tooltips',
                    'title' => $this->__('Used to determine moderator user accounts for sending email notifications.')
                ],
                'help' => $this->__('Used to determine moderator user accounts for sending email notifications.'),
                'data' => isset($this->moduleVars['moderationGroupForEntries']) ? $this->moduleVars['moderationGroupForEntries'] : '',
                'attr' => [
                    'maxlength' => 255,
                    'title' => $this->__('Choose the moderation group for entries.')
                ],// Zikula core should provide a form type for this to hide entity details
                'class' => 'ZikulaGroupsModule:GroupEntity',
                'choice_label' => 'name',
                'choice_value' => 'gid'
            ])
        ;
    }

    /**
     * Adds fields for list views fields.
     *
     * @param FormBuilderInterface $builder The form builder
     * @param array                $options The options
     */
    public function addListViewsFields(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('entryEntriesPerPage', IntegerType::class, [
                'label' => $this->__('Entry entries per page') . ':',
                'label_attr' => [
                    'class' => 'tooltips',
                    'title' => $this->__('The amount of entries shown per page')
                ],
                'help' => $this->__('The amount of entries shown per page'),
                'required' => false,
                'data' => isset($this->moduleVars['entryEntriesPerPage']) ? intval($this->moduleVars['entryEntriesPerPage']) : intval(10),
                'empty_data' => intval('10'),
                'attr' => [
                    'maxlength' => 255,
                    'title' => $this->__('Enter the entry entries per page.') . ' ' . $this->__('Only digits are allowed.')
                ],'scale' => 0
            ])
            ->add('linkOwnEntriesOnAccountPage', CheckboxType::class, [
                'label' => $this->__('Link own entries on account page') . ':',
                'label_attr' => [
                    'class' => 'tooltips',
                    'title' => $this->__('Whether to add a link to entries of the current user on his account page')
                ],
                'help' => $this->__('Whether to add a link to entries of the current user on his account page'),
                'required' => false,
                'data' => (bool)(isset($this->moduleVars['linkOwnEntriesOnAccountPage']) ? $this->moduleVars['linkOwnEntriesOnAccountPage'] : true),
                'attr' => [
                    'title' => $this->__('The link own entries on account page option.')
                ],
            ])
        ;
    }

    /**
     * Adds fields for integration fields.
     *
     * @param FormBuilderInterface $builder The form builder
     * @param array                $options The options
     */
    public function addIntegrationFields(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('enabledFinderTypes', ChoiceType::class, [
                'label' => $this->__('Enabled finder types') . ':',
                'label_attr' => [
                    'class' => 'tooltips',
                    'title' => $this->__('Which sections are supported in the Finder component (used by Scribite plug-ins).')
                ],
                'help' => $this->__('Which sections are supported in the Finder component (used by Scribite plug-ins).'),
                'data' => isset($this->moduleVars['enabledFinderTypes']) ? $this->moduleVars['enabledFinderTypes'] : '',
                'empty_data' => '',
                'attr' => [
                    'title' => $this->__('Choose the enabled finder types.')
                ],'choices' => [
                    $this->__('Entry') => 'entry'
                ],
                'choices_as_values' => true,
                'multiple' => true
            ])
        ;
    }

    /**
     * @inheritDoc
     */
    public function getBlockPrefix()
    {
        return 'mueternizermodule_config';
    }
}
