<?php
/**
 * Eternizer.
 *
 * @copyright Michael Ueberschaer
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package Eternizer
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://www.webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.4 (http://modulestudio.de) at Wed Jan 04 16:43:44 CET 2012.
 */

/**
 * Installer implementation class
 */
class Eternizer_Installer extends Eternizer_Base_Installer
{
    /**
     * Upgrade the Eternizer application from an older version.
     *
     * If the upgrade fails at some point, it returns the last upgraded version.
     *
     * @param integer $oldversion Version to upgrade from.
     *
     * @return boolean True on success, false otherwise.
     */
    public function upgrade($oldversion)
    {
        // Upgrade dependent on old version number
        switch ($oldversion) {
        	case '1.0a':
        	case '1.0':
        	case '1.1':
            $profile = ModUtil::getVar('Eternizer', 'profile');

            if (DataUtil::is_serialized($profile)) {
                $profile = unserialize($profile);
            }
            
            $profile = ModUtil::setVar('Eternizer', 'profile', $profile);
            case '1.1.1':
                // TODO we have to implement putting the datas into the new table
                // ...
                        
            break;
        }
        
    return true;
    }
}
