<?php
/**
 * Eternizer.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link http://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace MU\EternizerModule\DependencyInjection;

use MU\EternizerModule\DependencyInjection\Base\AbstractMUEternizerExtension;

/**
 * Implementation class for service definition loader using the DependencyInjection extension.
 */
class MUEternizerExtension extends AbstractMUEternizerExtension
{
    // custom enhancements can go here
}
