<?php
/**
 * Eternizer.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://www.webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.7.0 (http://modulestudio.de).
 */

namespace MU\EternizerModule\Api;


use ModUtil;
use SecurityUtil;
use Zikula\Core\Api\AbstractApi;

use MU\EternizerModule\Api\Base\AdminApi as BaseAdminApi;

/**
 * This is the Admin api helper class.
 */
class AdminApi extends BaseAdminApi
{
    /**
     * get available Admin panel links
     *
     * @return array Array of admin links
     */
    public function getLinks()
    {
        $links = array();
        $router = $this->get('router');
        $request = $this->get('request');

        if (SecurityUtil::checkPermission($this->name . '::', '::', ACCESS_READ)) {
            $links[] = array('url' => $router->generate('mueternizermodule_user_index'),
                'text' => $this->__('Frontend'),
                'title' => $this->__('Switch to user area.'),
                'class' => 'home');
        }
        
        $controllerHelper = $this->get('mueternizermodule.controller_helper');
        $utilArgs = array('api' => 'admin', 'action' => 'getLinks');
        $allowedObjectTypes = $controllerHelper->getObjectTypes('api', $utilArgs);
        
        $currentType = $request->query->filter('type', 'entry', false, FILTER_SANITIZE_STRING);
        $currentLegacyType = $request->query->filter('lct', 'user', false, FILTER_SANITIZE_STRING);
        $permLevel = in_array('admin', array($currentType, $currentLegacyType)) ? ACCESS_ADMIN : ACCESS_READ;
             
        if (in_array('entry', $allowedObjectTypes)
            && SecurityUtil::checkPermission($this->name . ':Entry:', '::', $permLevel)) {
            $links[] = array('url' => $router->generate('mueternizermodule_entry_view', array('lct' => 'admin')),
                'text' => $this->__('Entries'),
                'title' => $this->__('Entry list'));
        }
        if (SecurityUtil::checkPermission($this->name . '::', '::', ACCESS_ADMIN)) {
            $links[] = array('url' => $router->generate('mueternizermodule_admin_config'),
                             'text' => $this->__('Configuration'),
                             'title' => $this->__('Manage settings for this application'),
                             'icon' => 'wrench');
        }
        return $links;
    }
}
