<?php
/**
 * Eternizer.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://www.webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.7.0 (http://modulestudio.de).
 */

namespace MU\EternizerModule\Form\Handler\Admin;

use MU\EternizerModule\Form\Handler\Admin\Base\ConfigHandler as BaseConfigHandler;

/**
 * Configuration handler implementation class.
 */
class ConfigHandler extends BaseConfigHandler
{
    // feel free to extend the base handler class here
}
